# Generated by Django 5.2 on 2026-09-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nama')),
                ('slug', models.SlugField(blank=True, help_text='Dibiarkan kosong = dibuat otomatis dari nama.', max_length=60, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Teknologi',
                'verbose_name_plural': 'Teknologi',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='judul')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='slug')),
                ('summary', models.CharField(help_text='1–2 kalimat untuk kartu project & meta description.', max_length=200, verbose_name='ringkasan')),
                ('description', models.TextField(help_text='Penjelasan lengkap: latar belakang, peran Anda, solusi, dan hasil. Pisahkan paragraf dengan baris baru.', verbose_name='deskripsi')),
                ('thumbnail', models.ImageField(blank=True, upload_to='projects/thumbnails/', verbose_name='thumbnail')),
                ('demo_url', models.URLField(blank=True, verbose_name='tautan demo')),
                ('repo_url', models.URLField(blank=True, verbose_name='tautan source code')),
                ('is_published', models.BooleanField(default=True, verbose_name='publikasikan')),
                ('is_featured', models.BooleanField(default=False, help_text='Project unggulan tampil di landing page.', verbose_name='unggulan')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Semakin kecil, semakin depan.', verbose_name='urutan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='diperbarui')),
                ('tech_stack', models.ManyToManyField(blank=True, related_name='projects', to='projects.technology', verbose_name='tech stack')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ('order', '-created_at'),
            },
        ),
    ]
