# Generated by Django 5.2 on 2026-09-07 12:17

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='JPG/PNG/WebP, maksimal 2 MB.', upload_to='projects/thumbnails/', validators=[core.validators.validate_image_upload], verbose_name='thumbnail'),
        ),
    ]
