# Generated by Django 4.2 on 2026-09-07 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100, verbose_name='posisi')),
                ('company', models.CharField(max_length=100, verbose_name='perusahaan/instansi')),
                ('description', models.TextField(blank=True, help_text='Poin pencapaian. Pisahkan dengan baris baru.', verbose_name='deskripsi')),
                ('start_date', models.DateField(verbose_name='mulai')),
                ('end_date', models.DateField(blank=True, help_text='Kosongkan jika masih berjalan.', null=True, verbose_name='selesai')),
            ],
            options={
                'verbose_name': 'Pengalaman',
                'verbose_name_plural': 'Pengalaman',
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='nama lengkap')),
                ('tagline', models.CharField(help_text='Kalimat singkat peran/posisi. Contoh: Fullstack Developer — Django & TailwindCSS.', max_length=120, verbose_name='tagline')),
                ('intro', models.TextField(help_text='1–2 kalimat pembuka pada bagian hero.', verbose_name='intro hero')),
                ('about', models.TextField(help_text='Bio lengkap. Pisahkan paragraf dengan baris baru.', verbose_name='tentang saya')),
                ('photo', models.ImageField(blank=True, upload_to='profile/', verbose_name='foto')),
                ('cv_file', models.FileField(blank=True, upload_to='cv/', verbose_name='file CV')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='telepon')),
                ('location', models.CharField(blank=True, help_text='Contoh: Jakarta, Indonesia', max_length=100, verbose_name='lokasi')),
                ('open_to_work', models.BooleanField(default=True, help_text='Menampilkan badge status ketersediaan pada bagian hero.', verbose_name='terbuka untuk peluang')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profil',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nama')),
                ('category', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('database', 'Database'), ('tools', 'Tools & DevOps'), ('other', 'Lainnya')], default='backend', max_length=20, verbose_name='kategori')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='urutan')),
            ],
            options={
                'verbose_name': 'Keahlian',
                'verbose_name_plural': 'Keahlian',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Nama platform. Contoh: GitHub, LinkedIn, Instagram, X, YouTube.', max_length=30, verbose_name='label')),
                ('url', models.URLField(verbose_name='tautan')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='urutan')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='core.profile')),
            ],
            options={
                'verbose_name': 'Tautan Media Sosial',
                'verbose_name_plural': 'Tautan Media Sosial',
                'ordering': ('order', 'id'),
            },
        ),
    ]
