# Generated by Django 5.2 on 2026-09-07 12:17

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cv_file',
            field=models.FileField(blank=True, help_text='PDF/DOC/DOCX, maksimal 5 MB.', upload_to='cv/', validators=[core.validators.validate_document_upload], verbose_name='file CV'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, help_text='JPG/PNG/WebP, maksimal 2 MB.', upload_to='profile/', validators=[core.validators.validate_image_upload], verbose_name='foto'),
        ),
    ]
