# Generated by Django 5.2 on 2026-09-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nama')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('subject', models.CharField(max_length=150, verbose_name='subjek')),
                ('message', models.TextField(verbose_name='isi pesan')),
                ('ip_address', models.GenericIPAddressField(blank=True, editable=False, null=True, verbose_name='alamat IP')),
                ('is_read', models.BooleanField(default=False, verbose_name='sudah dibaca')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='diterima')),
            ],
            options={
                'verbose_name': 'Pesan Kontak',
                'verbose_name_plural': 'Pesan Kontak',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['is_read', 'created_at'], name='contact_con_is_read_252076_idx')],
            },
        ),
    ]
