# Generated by Django 5.2 on 2026-09-07 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='nama')),
                ('slug', models.SlugField(blank=True, help_text='Dibiarkan kosong = dibuat otomatis dari nama.', max_length=70, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='deskripsi')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategori',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='nama')),
                ('slug', models.SlugField(blank=True, help_text='Dibiarkan kosong = dibuat otomatis dari nama.', unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tag',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='judul')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='slug')),
                ('cover_image', models.ImageField(blank=True, upload_to='blog/covers/', verbose_name='gambar sampul')),
                ('excerpt', models.CharField(blank=True, help_text='1–2 kalimat untuk kartu & meta description. Dibiarkan kosong = digenerate otomatis dari isi.', max_length=300, verbose_name='ringkasan')),
                ('content', models.TextField(help_text='Ditulis dengan format Markdown: heading, list, code block, tabel.', verbose_name='isi')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Terpublikasi')], default='draft', max_length=10, verbose_name='status')),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='dipublikasikan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='diperbarui')),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='penulis')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog.category', verbose_name='kategori')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='blog.tag', verbose_name='tag')),
            ],
            options={
                'verbose_name': 'Tulisan',
                'verbose_name_plural': 'Tulisan',
                'ordering': ('-published_at', '-created_at'),
                'indexes': [models.Index(fields=['status', 'published_at'], name='blog_post_status_5b2843_idx')],
            },
        ),
    ]
