# Generated by Django 5.2 on 2026-09-07 12:17

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='JPG/PNG/WebP, maksimal 2 MB.', upload_to='blog/covers/', validators=[core.validators.validate_image_upload], verbose_name='gambar sampul'),
        ),
    ]
